// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-07-19 12:13:31.403597 +0800 CST m=+0.615077884

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/limit/countreject": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "limit"
                ],
                "summary": "计数拒流，每秒超过指定次数会拒流掉",
                "responses": {
                    "200": {
                        "description": "成功会返回ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "失败返回reject"
                    }
                }
            }
        },
        "/limit/randomreject": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "limit"
                ],
                "summary": "随机拒流",
                "responses": {
                    "200": {
                        "description": "成功会返回ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "失败返回reject"
                    }
                }
            }
        },
        "/limit/slidewindowsreject": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "limit"
                ],
                "summary": "滑动窗口计数拒流，每秒超过指定次数会拒流掉",
                "responses": {
                    "200": {
                        "description": "成功会返回ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "失败返回reject"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "ping接口，用于测试是否调通",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "base"
                ],
                "summary": "接口探活",
                "parameters": [
                    {
                        "type": "string",
                        "description": "参数描述",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
